export const STANDALONE_RUNTIME = String.raw`
(()=>{
const payload=JSON.parse(document.getElementById('mo-story').textContent);
const story=payload.document;
const scenes=new Map(story.scenes.map(scene=>[scene.id,scene]));
const kernel=createPlayerStateMachine(story,undefined,createRuleRuntime);
let state=kernel.snapshot();
const q=selector=>document.querySelector(selector);
const saveKey=slot=>'mo.save.'+story.id+'.'+slot;
const interpolate=text=>text.replace(/\{\{\$vars\.([\w.-]+)\}\}/g,(_,id)=>String(state.variables[id]??''));
const button=(label,action,className='mo-standalone-menu-button')=>{const node=document.createElement('button');node.type='button';node.textContent=label;node.className=className;node.onclick=action;return node};
for(const [id,source] of Object.entries(payload.runtimeFunctions)){const contribution=new Function('return ('+source+')')();kernel.registerRuntimeFunction(id,(...args)=>contribution(kernel.runtimeVariables(),...args))}
function appendMessage(className,html){const stream=q('[data-message-stream]');if(!stream)return;const row=document.createElement('div');row.className='chat-message '+className;const bubble=document.createElement('div');bubble.className='chat-bubble '+(className.includes('right')?'chat-bubble-choice':'chat-bubble-story');bubble.innerHTML=html;row.append(bubble);stream.append(row);stream.parentElement.scrollTop=stream.parentElement.scrollHeight}
function renderCharacters(){if(!state.scene)return;const characters=state.scene.media.characters||[];const layer=q('[data-character-layer]');if(layer){const nodes=characters.map(character=>{const image=document.createElement('img');image.src=payload.assets[character.assetId]||'';image.alt=character.label||character.fileName||'人物';image.className='mo-character-'+(character.horizontalPosition||'center');image.style.transform='scale('+(character.scale||1)+')';return image});layer.replaceChildren(...nodes);return}const media=q('[data-scene-media]');const stream=q('[data-message-stream]');for(const character of characters){const image=document.createElement('img');image.src=payload.assets[character.assetId]||'';image.alt=character.label||character.fileName||'人物';if(stream){const row=document.createElement('div');row.className='chat-message chat-message-left';image.className='chat-bubble chat-bubble-image';row.append(image);stream.append(row)}else if(media){const figure=document.createElement('figure');figure.dataset.characterFallback='true';const caption=document.createElement('figcaption');caption.textContent=character.label||character.fileName||'人物';figure.append(image,caption);media.append(figure)}}}
function renderMedia(){if(!state.scene)return;const media=q('[data-scene-media]');const background=state.scene.media.background;const url=background&&payload.assets[background.assetId];if(media){media.style.backgroundImage=url?'url("'+url+'")':'';media.setAttribute('aria-label',background?(background.label||background.fileName):'')}const stream=q('[data-message-stream]');if(stream&&url){const row=document.createElement('div');row.className='chat-message chat-message-left';const image=document.createElement('img');image.className='chat-bubble chat-bubble-image';image.src=url;image.alt=background.label||background.fileName||'场景图片';row.append(image);stream.append(row)}renderCharacters()}
function renderChoices(){if(!state.scene)return;const choiceRoot=q('[data-scene-choices]');if(!choiceRoot)return;const choiceClass=choiceRoot.dataset.choiceClass||'mo-story-choice';const nodes=state.availableChoices.map(choice=>button(choice.text,()=>choose(choice),choiceClass));for(const hotspot of state.scene.media.hotspots||[])nodes.push(button(hotspot.label,()=>apply({type:'hotspot',hotspotId:hotspot.id}),choiceClass));if(state.status==='ended')nodes.push(button('重新开始',start,choiceClass));choiceRoot.replaceChildren(...nodes);const fallback=q('[data-hotspot-fallback]');if(fallback)fallback.replaceChildren(...(state.scene.media.hotspots||[]).map(hotspot=>button(hotspot.label,()=>apply({type:'hotspot',hotspotId:hotspot.id}),'mo-story-choice')))}
function renderStatus(){const status=q('[data-player-status]');if(!status)return;const display=story.variables.filter(variable=>variable.displayInPlayer).sort((a,b)=>(a.displayOrder||0)-(b.displayOrder||0));status.hidden=story.presentation.settings.showHud===false;status.textContent=display.map(variable=>variable.label+': '+String(state.variables[variable.id])).join(' · ')}
function render(){if(!state.scene)return;const shell=q('[data-player-template]');if(shell)shell.dataset.sceneVariant=story.presentation.sceneVariants[state.scene.id]||'default';const html=interpolate(payload.renderedScenes[state.scene.id]||'');const speaker=q('[data-scene-speaker]');if(speaker)speaker.textContent=state.scene.content.speaker||'';const text=q('[data-scene-text]');if(text)text.innerHTML=html;renderMedia();if(q('[data-message-stream]'))appendMessage('chat-message-left',html);renderChoices();renderStatus();const ending=q('[data-player-ending]');if(ending)ending.hidden=state.status!=='ended'}
function apply(command){state=kernel.dispatch(command);render();return state}
function choose(choice){if(q('[data-message-stream]'))appendMessage('chat-message-right',choice.text);apply({type:'choose',choiceId:choice.id})}
function showPlayer(){const startRoot=q('[data-player-start]');const main=q('[data-player-main]');if(startRoot)startRoot.hidden=true;if(main)main.hidden=false}
function clearMessages(){const stream=q('[data-message-stream]');if(!stream)return;const anchors=[q('[data-scene-media]'),q('[data-scene-speaker]'),q('[data-scene-text]')].filter(Boolean);stream.replaceChildren(...anchors)}
function start(){showPlayer();closeMenu();clearMessages();apply({type:'start'})}
function save(slot){if(!state.scene)return;localStorage.setItem(saveKey(slot),JSON.stringify({version:1,save:kernel.save(),savedAt:new Date().toISOString()}));renderMenu('save')}
function readSave(slot){try{const value=localStorage.getItem(saveKey(slot));if(!value)return null;const data=JSON.parse(value);return data.version===1&&data.save&&scenes.has(data.save.sceneId)?data:null}catch{return null}}
function load(slot){const data=readSave(slot);if(!data)return;showPlayer();clearMessages();state=kernel.load(data.save);closeMenu();render()}
function closeMenu(){const overlay=q('[data-menu-overlay]');if(overlay)overlay.hidden=true}
function menuBack(){renderMenu('main')}
function menuTitle(value){const title=q('[data-menu-title]');if(title)title.textContent=value}
function slotView(mode){const root=document.createElement('div');root.className='mo-standalone-menu-list';root.append(button('返回',menuBack));for(let slot=1;slot<=3;slot++){const data=readSave(slot);const item=document.createElement('div');item.className='mo-standalone-menu-item';const heading=document.createElement('strong');heading.textContent='槽位 '+slot;const detail=document.createElement('div');detail.className='mo-standalone-menu-meta';detail.textContent=data?(scenes.get(data.save.sceneId)?.content.speaker||'场景 '+data.save.sceneId)+' · '+new Date(data.savedAt).toLocaleString():'空槽位';item.append(heading,detail,button(mode==='save'?'保存':'读取',()=>mode==='save'?save(slot):load(slot)));root.append(item)}return root}
function mapView(){const root=document.createElement('div');root.className='mo-standalone-menu-list';root.append(button('返回',menuBack));for(const visit of state.visits){const scene=scenes.get(visit.sceneId);const label=scene?.tags?.[0]||scene?.content?.speaker||'场景 '+visit.sceneId;root.append(button(label+' · 访问 '+visit.count+' 次',()=>{closeMenu();apply({type:'jump',sceneId:visit.sceneId})}))}if(state.visits.length===0){const empty=document.createElement('p');empty.textContent='尚未访问任何场景';root.append(empty)}return root}
function playerView(){const root=document.createElement('div');root.className='mo-standalone-menu-list';root.append(button('返回',menuBack));const attributes=document.createElement('section');attributes.className='mo-standalone-menu-item';const heading=document.createElement('h3');heading.textContent='属性';attributes.append(heading);for(const variable of story.variables.filter(item=>item.displayInPlayer)){const row=document.createElement('div');row.textContent=variable.label+': '+String(state.variables[variable.id]);attributes.append(row)}const inventory=document.createElement('section');inventory.className='mo-standalone-menu-item';const inventoryTitle=document.createElement('h3');inventoryTitle.textContent='背包';inventory.append(inventoryTitle);const items=story.variables.filter(item=>item.type==='boolean'&&state.variables[item.id]===true);inventory.append(...(items.length?items.map(item=>{const row=document.createElement('div');row.textContent=item.label;return row}):[Object.assign(document.createElement('p'),{textContent:'暂无物品'})]));root.append(attributes,inventory);return root}
function renderMenu(view='main'){const content=q('[data-menu-content]');if(!content)return;content.replaceChildren();if(view==='save'){menuTitle('保存游戏');content.append(slotView('save'));return}if(view==='load'){menuTitle('继续游戏');content.append(slotView('load'));return}if(view==='map'){menuTitle('世界地图');content.append(mapView());return}if(view==='player'){menuTitle('玩家');content.append(playerView());return}menuTitle('游戏菜单');const list=document.createElement('div');list.className='mo-standalone-menu-list';list.append(button('新游戏',()=>{if(confirm('确定要开始新游戏吗？当前进度将会丢失。'))start()}),button('继续游戏',()=>renderMenu('load')),button('保存游戏',()=>renderMenu('save')),button('世界地图',()=>renderMenu('map')),button('玩家',()=>renderMenu('player')),button('退出游戏',exit));content.append(list)}
function openMenu(){const overlay=q('[data-menu-overlay]');if(!overlay)return;renderMenu();overlay.hidden=false}
function exit(){window.close();if(!window.closed&&history.length>1)window.history.back()}
q('[data-player-menu]')?.addEventListener('click',openMenu);q('[data-menu-close]')?.addEventListener('click',closeMenu);q('[data-menu-overlay]')?.addEventListener('click',event=>{if(event.target===q('[data-menu-overlay]'))closeMenu()});q('[data-player-back]')?.addEventListener('click',exit);
document.addEventListener('click',event=>{const target=event.target.closest?.('[data-choice-id]');if(!target||!state.scene)return;const choice=state.availableChoices.find(item=>item.id===target.getAttribute('data-choice-id'));if(choice)choose(choice)});
const shell=q('[data-player-template]');if(shell)shell.style.setProperty('--text-scale',String(story.presentation.settings.textScale||1));
const startRoot=q('[data-player-start]');const hasSave=[1,2,3].some(slot=>readSave(slot));const continueButton=q('[data-start-continue]');if(continueButton){continueButton.hidden=!hasSave;continueButton.onclick=()=>{showPlayer();openMenu()}}q('[data-start-new]')?.addEventListener('click',start);q('[data-start-exit]')?.addEventListener('click',exit);if(!startRoot)start();
})();`;
